# SLSA Builder Configuration

# Build command to create Python distribution
command = ["python", "-m", "build"]

# Path to the built distribution files
artifact_path = "dist/*"

# Additional build settings
[build]
expected_files = [
    "dist/*.whl",    # wheel distribution
    "dist/*.tar.gz"  # source distribution
] 